### ISSUE TITLE
Missing .env file?

### ISSUE THREAD

**Issue by MagnusIIIBR** [codrin-axinte/Eve-Corp#2]
I tried run the app, but, i see this message:

![image](https://user-images.githubusercontent.com/9530663/47533202-32406400-d889-11e8-83b2-e1569ff312ad.png)

**Comment by codrin-axinte** [comment]
Hi,
You have to rename the .env.example file to .env and make sure you've set the dataBase credentials correctly. I suggest you to visit the laravel documentation at https://laravel.com or if you want video tutorials you can check the https://laracasts.com.

**Comment by MagnusIIIBR** [comment]
Thankx @codrin-axinte .

You will make a documentation of this cms? 
You make a great tool bro. 
Congratz :D

**Comment by codrin-axinte** [comment]
I will write some documentation, well at least for installation for now.
