### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by CokkocZateki** [codrin-axinte/Eve-Corp#3]
Hi
Sorry i couldnt find any other method of trying to get a hold of you.  How would one install this onto a server.

Any quick ref guides

**Comment by codrin-axinte** [comment]
First of all make sure your server meets the requirements:

PHP >= 7.1.3
OpenSSL PHP Extension
PDO PHP Extension
Mbstring PHP Extension
Tokenizer PHP Extension
XML PHP Extension
Ctype PHP Extension
JSON PHP Extension
BCMath PHP Extension

After that you can follow any laravel installation on a server.
https://www.youtube.com/watch?v=6g8G3YQtQt4
